mainPage:
    path: /
    controller: App\Controller\SiteController::index
lectures_list:
    path: /lecture/list
    controller: App\Controller\SiteController::lectures_list
tests_list:
    path: /test/list
    controller: App\Controller\SiteController::tests_list
about:
    path: /about
    controller: App\Controller\SiteController::about
cab:
    path: /userCab
    controller: App\Controller\SiteController::userCab
login:
    path: /login
    controller: App\Controller\SiteController::login
reg:
    path: /reg
    controller: App\Controller\SiteController::reg
logout:
    path: /logout
    controller: App\Controller\SiteController::logout
lecture:
    path: /lecture/{id}
    controller: App\Controller\SiteController::showLecture
test:
    path: /test/{id}
    controller: App\Controller\SiteController::showTest
admin:
    path: /admin
    controller: App\Controller\AdminController::admin
createLecture:
    path: /create/lecture
    controller: App\Controller\AdminController::createLecture
editLecture:
    path: /edit/lecture/{id}
    controller: App\Controller\AdminController::editLecture
deleteLecture:
    path: /delete/lecture/{id}
    controller: App\Controller\AdminController::deleteLecture
addTest:
    path: /create/test
    controller: App\Controller\AdminController::createTest
deleteTest:
    path: /delete/test/{id}
    controller: App\Controller\AdminController::deleteTest
deleteUser:
    path: /user/delete/{id}
    controller: App\Controller\AdminController::deleteUser
